apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: bowtie2-build-index-v1-submittable
spec:
  entrypoint: build-index
  imagePullSecrets:
    - name: ebi-gl-cr-pull-token
  templates:
    - name: build-index
      inputs:
        parameters:
          - name: prefix
          - name: filename
          - name: bt2_index_base
          - name: threads
            value: "8"
        artifacts:
          - name: my-reference-genome-fasta
            path: /results/{{inputs.parameters.filename}}
            s3:
              key: "{{inputs.parameters.prefix}}{{inputs.parameters.filename}}"
      container:
        image: dockerhub.ebi.ac.uk/ensreg/workflows/container-images/bowtie2_samtools:2.4.5_1.15.1
        command: [ bash, -c ]
        args: [ "bowtie2-build --threads {{inputs.parameters.threads}} \
        {{inputs.parameters.filename}} \
        {{inputs.parameters.bt2_index_base}}" ]
        resources:
          requests:
            cpu: 7900m
            memory: 28Gi
          limits:
            cpu: 8900m
            memory: 30Gi
      outputs:
        artifacts:
          - name: reference-genome-fasta
            path: /home/ensreg/workdir/
            s3:
              key: "{{inputs.parameters.prefix}}{{inputs.parameters.bt2_index_base}}.tar.gz"
