apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: controls-peak-calling-for-mask-file-v1-submittable
spec:
  entrypoint: controls-peak-calling-for-mask-file

  imagePullSecrets:
    - name: ghcr-pull-token

  templates:
    - name: controls-peak-calling-for-mask-file
      parallelism: 15
      inputs:
        parameters:
          - name: peak_calling_tasks
          - name: chipmentation
          - name: overwrite-results
          - name: kubeconfig-path
      dag:
        tasks:
          - name: execute-peak-calling-task
            template: peak-calling-task
            arguments:
              parameters:
                - name: task-payload
                  value: "{{item}}"
                - name: assembly_id
                  value: "{{item.assembly_id}}"
                - name: out_basename
                  value: "{{item.out_basename}}"
                - name: out_s3_prefix
                  value: "{{item.out_s3_prefix}}"
                - name: alignment_files_total_size
                  value: "{{item.alignment_files_total_size}}"
                - name: signals
                  value: "{{item.signals}}"
                - name: chipmentation
                  value: "{{inputs.parameters.chipmentation}}"
                - name: overwrite-results
                  value: "{{inputs.parameters.overwrite-results}}"
                - name: kubeconfig-path
                  value: "{{inputs.parameters.kubeconfig-path}}"
            withParam: "{{inputs.parameters.peak_calling_tasks}}"


    - name: peak-calling-task
      parallelism: 1
      inputs:
        parameters:
          - name: task-payload
          - name: assembly_id
          - name: out_basename
          - name: out_s3_prefix
          - name: alignment_files_total_size
          - name: signals
          - name: kubeconfig-path
          - name: chipmentation
          - name: overwrite-results
          - name: force-update-task-markers
            value: "false"

      dag:
        tasks:
          - name: check-if-bed-file-already-in-s3-bucket
            templateRef:
              name: check-s3-object-exists-v1-submittable
              template: check-s3-object-exists
            arguments:
              parameters:
                - name: s3-key
                  value: "{{inputs.parameters.out_s3_prefix}}{{inputs.parameters.out_basename}}.bed"

          - name: get-peak-calling-pvc-size
            depends: check-if-bed-file-already-in-s3-bucket.Succeeded
            when: "{{tasks.check-if-bed-file-already-in-s3-bucket.outputs.parameters.s3-object-exists}} == false"
            templateRef:
              name: compute-pvc-size-v1-submittable
              template: compute-pvc-size
            arguments:
              parameters:
                - name: associated_files_size
                  value: "{{inputs.parameters.alignment_files_total_size}}"
                - name: size_factor
                  value: "3.5"

          - name: create-peak-calling-pvc
            depends: "get-peak-calling-pvc-size.Succeeded"
            templateRef:
              name: create-nfs-pvc-kubectl-v1-submittable
              template: create-nfs-pvc-kubectl
            arguments:
              parameters:
                - name: pvc-size
                  value: "{{tasks.get-peak-calling-pvc-size.outputs.parameters.pvc-size-formatted}}"
                - name: kubeconfig-path
                  value: "{{inputs.parameters.kubeconfig-path}}"

          - name: execute-sort-alignments-by-queryname
            depends: create-peak-calling-pvc
            template: sort-alignments-by-queryname
            arguments:
              parameters:
                - name: sort_alignment_params
                  value: "{{item}}"
                # PVC in which to store so_queryname bams
                - name: out-pvc-name
                  value: "{{tasks.create-peak-calling-pvc.outputs.parameters.pvc-name}}"
                - name: kubeconfig-path
                  value: "{{inputs.parameters.kubeconfig-path}}"
            withParam: "{{inputs.parameters.signals}}"

          - name: execute-genrich-controls
            depends: execute-sort-alignments-by-queryname
            template: genrich-controls
            arguments:
              parameters:
                - name: out_bed_filename
                  value: "{{inputs.parameters.out_basename}}.bed"
                - name: out_pileup_filename
                  value: "{{inputs.parameters.out_basename}}_pileup.log"
                - name: out_pq_file_filename
                  value: "{{inputs.parameters.out_basename}}_pqval.log"
                - name: out_log_filename
                  value: "{{inputs.parameters.out_basename}}_run.log"
                - name: out_s3_prefix
                  value: "{{inputs.parameters.out_s3_prefix}}"
                - name: chipmentation
                  value: "{{inputs.parameters.chipmentation}}"
                - name: signals-pvc
                  value: "{{tasks.create-peak-calling-pvc.outputs.parameters.pvc-name}}"


          - name: delete-peak-calling-pvc
            depends: execute-genrich-controls
            templateRef:
              name: delete-patch-pvc-kubectl-v1-submittable
              template: delete-patch-pvc-kubectl
            arguments:
              parameters:
                - name: pvc-name
                  value: "{{tasks.create-peak-calling-pvc.outputs.parameters.pvc-name}}"
                - name: kubeconfig-path
                  value: "{{inputs.parameters.kubeconfig-path}}"


    - name: sort-alignments-by-queryname
      inputs:
        parameters:
          # Bam file as input
          - name: sort_alignment_params
          # PVC in which to store bedgraph
          - name: out-pvc-name
          - name: kubeconfig-path
      dag:
        tasks:
          - name: get-pvc-size
            templateRef:
              name: compute-pvc-size-v1-submittable
              template: compute-pvc-size
            arguments:
              parameters:
                - name: associated_files_size
                  value: "{{=jsonpath(inputs.parameters.sort_alignment_params, '$.file_size')}}"
                - name: size_factor
                  value: "1.5"

          - name: execute-sort-alignment-by-queryname
            depends: get-pvc-size
            templateRef:
              name: sort-alignment-by-queryname-pvc-callable-v1-submittable
              template: sort-alignment-by-queryname-pvc-callable
            arguments:
              parameters:
                - name: basename
                  value: "{{=jsonpath(inputs.parameters.sort_alignment_params, '$.basename')}}"
                - name: filename
                  value: "{{=jsonpath(inputs.parameters.sort_alignment_params, '$.filename')}}"
                - name: s3_key
                  value: "{{=jsonpath(inputs.parameters.sort_alignment_params, '$.s3_key')}}"
                - name: pvc-size
                  value: "{{tasks.get-pvc-size.outputs.parameters.pvc-size-formatted}}"
                - name: kubeconfig-path
                  value: "{{inputs.parameters.kubeconfig-path}}"
                - name: out-pvc-name
                  value: "{{inputs.parameters.out-pvc-name}}"



    - name: genrich-controls
      retryStrategy:
        limit: "3"
        retryPolicy: "OnError"
      inputs:
        parameters:
          - name: out_bed_filename
          - name: out_pileup_filename
          - name: out_pq_file_filename
          - name: out_log_filename
          - name: out_s3_prefix
          - name: chipmentation
          - name: signals-pvc
      container:
        workingDir: /mnt/vol
        image: ghcr.io/daugo/ensembl-reg-genrich:latest
        command: [ bash, -c, -ue, -o, xtrace ]
        args: [ "ls -altrh \
                && SIGNAL_BAM_FILES=$(ls -m *.bam | xargs echo | sed 's/ //g') \
                && GENRICH_ARGS_1st_RUN=(
                  -t ${SIGNAL_BAM_FILES}
                  -o q_value_run_{{inputs.parameters.out_bed_filename}}
                  -f {{inputs.parameters.out_pileup_filename}}
                  -r
                  -q 0.1
                  -s 20
                  -e MT
                  -v
                ) \
                && if [[ {{inputs.parameters.chipmentation}} == 'true' ]]; then GENRICH_ARGS_1st_RUN+=(-j); fi \
                && Genrich ${GENRICH_ARGS_1st_RUN[@]} \
                | tee {{inputs.parameters.out_log_filename}} \
                && ls -altrh \
                && GENRICH_ARGS_2nd_RUN=(
                  -P
                  -o {{inputs.parameters.out_bed_filename}}
                  -f {{inputs.parameters.out_pileup_filename}}
                  -r
                  -p 0.05
                  -s 20
                  -e MT
                  -v
                ) \
                && if [[ {{inputs.parameters.chipmentation}} == 'true' ]]; then GENRICH_ARGS_2nd_RUN+=(-j); fi \
                && Genrich ${GENRICH_ARGS_2nd_RUN[@]} \
                | tee {{inputs.parameters.out_log_filename}} \
                && ls -altrh" ]
        resources:
          limits:
            cpu: 4900m
            memory: 58Gi
          requests:
            cpu: 4700m
            memory: 52Gi
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: "{{inputs.parameters.signals-pvc}}"
      outputs:
        artifacts:
          - name: final_bed
            path: /mnt/vol/{{inputs.parameters.out_bed_filename}}
            archive:
              none: { }
            s3:
              key: "{{inputs.parameters.out_s3_prefix}}{{inputs.parameters.out_bed_filename}}"
          - name: pileup
            path: /mnt/vol/{{inputs.parameters.out_pileup_filename}}
            s3:
              key: "{{inputs.parameters.out_s3_prefix}}{{inputs.parameters.out_pileup_filename}}.tgz"
          - name: log_file
            path: /mnt/vol/{{inputs.parameters.out_log_filename}}
            archive:
              none: { }
            s3:
              key: "{{inputs.parameters.out_s3_prefix}}{{inputs.parameters.out_log_filename}}"
