# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: delete-task-marker-v1-submittable
spec:
  entrypoint: delete-task-marker
  imagePullSecrets:
    - name: ghcr-pull-token

  templates:
    - name: delete-task-marker
      retryStrategy:
        limit: "5"
        backoff:
          duration: "10s"
          factor: "2"
        retryPolicy: "OnError"
      inputs:
        parameters:
          - name: task-payload
          - name: task-type
          - name: dryrun
      dag:
        tasks:
          - name: compute-task-marker-name
            templateRef:
              name: compute-task-marker-name-v1-submittable
              template: compute-task-marker-name
            arguments:
              parameters:
                - name: task-payload
                  value: "{{inputs.parameters.task-payload}}"
                - name: task-type
                  value: "{{inputs.parameters.task-type}}"

          - name: check-if-task-marker-exists
            depends: compute-task-marker-name
            templateRef:
              name: check-s3-object-exists-v1-submittable
              template: check-s3-object-exists
            arguments:
              parameters:
                - name: s3-key
                  value: "{{tasks.compute-task-marker-name.outputs.result}}"

          - name: delete-rfs-alignment-marker
            depends: check-if-task-marker-exists
            when: "{{tasks.check-if-task-marker-exists.outputs.parameters.s3-object-exists}} == true && {{inputs.parameters.dryrun}} == false"
            templateRef:
              name: delete-s3-object-v1-submittable
              template: delete-s3-object
            arguments:
              parameters:
                - name: s3-key
                  value: "{{tasks.compute-task-marker-name.outputs.result}}"




