apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sort-alignment-by-queryname-pvc-callable-v1-submittable
spec:
  entrypoint: sort-alignment-by-queryname-pvc-callable
  imagePullSecrets:
    - name: ghcr-pull-token
  podGC:
    strategy: OnPodSuccess

  templates:
    - name: sort-alignment-by-queryname-pvc-callable
      inputs:
        parameters:
          # Bam file as input
          - name: basename
          - name: filename
          - name: s3_key
          - name: pvc-size
          - name: kubeconfig-path
          # PVC in which to store sorted bam
          - name: out-pvc-name

      dag:
        tasks:
          - name: create-samtools-sort-queryname-pvc
            templateRef:
              name: create-pvc-kubectl-v1-submittable
              template: create-pvc-kubectl
            arguments:
              parameters:
                - name: pvc-size
                  value: "{{inputs.parameters.pvc-size}}"
                - name: kubeconfig-path
                  value: "{{inputs.parameters.kubeconfig-path}}"

          - name: load-bam-to-pvc
            depends: create-samtools-sort-queryname-pvc
            templateRef:
              name: s3-object-to-pvc-v1-submittable
              template: s3-object-to-pvc
            arguments:
              parameters:
                - name: s3-key
                  value: "{{inputs.parameters.s3_key}}"
                - name: filename
                  value: "{{inputs.parameters.filename}}"
                - name: pvc-name
                  value: "{{tasks.create-samtools-sort-queryname-pvc.outputs.parameters.pvc-name}}"


          - name: execute-samtools-sort-by-queryname-cmd
            depends: load-bam-to-pvc
            template: samtools-sort-by-queryname-cmd
            arguments:
              parameters:
                - name: pvc-name
                  value: "{{tasks.create-samtools-sort-queryname-pvc.outputs.parameters.pvc-name}}"
                - name: filename
                  value: "{{inputs.parameters.filename}}"
                - name: out-pvc-name
                  value: "{{inputs.parameters.out-pvc-name}}"
                - name: out-filename
                  value: "so_queryname_{{inputs.parameters.basename}}.bam"
                - name: num-threads
                  value: "6"
                - name: mem-per-thread
                  value: "2G"

          - name: delete-samtools-sort-queryname-pvc
            depends: execute-samtools-sort-by-queryname-cmd
            templateRef:
              name: delete-patch-pvc-kubectl-v1-submittable
              template: delete-patch-pvc-kubectl
            arguments:
              parameters:
                - name: pvc-name
                  value: "{{tasks.create-samtools-sort-queryname-pvc.outputs.parameters.pvc-name}}"
                - name: kubeconfig-path
                  value: "{{inputs.parameters.kubeconfig-path}}"

    - name: samtools-sort-by-queryname-cmd
      retryStrategy:
        limit: "5"
        retryPolicy: "OnError"
      inputs:
        parameters:
          - name: pvc-name
          - name: filename
          - name: out-pvc-name
          - name: out-filename
          - name: num-threads
          - name: mem-per-thread
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: "{{inputs.parameters.pvc-name}}"
        - name: outputs
          persistentVolumeClaim:
            claimName: "{{inputs.parameters.out-pvc-name}}"
      container:
        workingDir: /mnt/vol
        image: ghcr.io/daugo/ensembl-reg-samtools:latest
        command: [ bash, -c, -uef, -o, xtrace ]
        args: [ "ls -altrh \
                && ls -altrh /mnt/out_vol/ \
                && rm -f /mnt/out_vol/{{inputs.parameters.out-filename}}* \
                && samtools view -@ {{inputs.parameters.num-threads}} -b -h -F 0x004 {{inputs.parameters.filename}} | \
                samtools sort -n \
                -@ {{inputs.parameters.num-threads}} \
                -m {{inputs.parameters.mem-per-thread}} \
                -o /mnt/out_vol/{{inputs.parameters.out-filename}} \
                && ls -altrh \
                && ls -altrh /mnt/out_vol/" ]
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol
          - name: outputs
            mountPath: /mnt/out_vol
        resources:
          limits:
            cpu: 6100m
            memory: 28Gi
          requests:
            cpu: 5800m
            memory: 24Gi



