apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: run-alignment-se-v2-submittable
spec:
  entrypoint: run-alignment
  podGC:
    strategy: OnPodSuccess
  imagePullSecrets:
    - name: ghcr-pull-token

  templates:
    - name: run-alignment
      inputs:
        parameters:
          # Input file
          - name: first_read_file_key
          - name: first_read_file_name
          - name: first_read_file_basename
          - name: bowtie2_index_key
          - name: bowtie2_index_basename
          # Output related
          - name: total_read_files_size
          - name: read_files_output_prefix
          - name: fastqc_outdir
          - name: fastqc_output_prefix
          - name: output_prefix
          - name: output_filename
          # Others
          - name: overwrite-results
          - name: kubeconfig-path
        artifacts:
          - name: run-payload
      dag:
        tasks:
          - name: compute-run-alignment-task-marker-name
            templateRef:
              name: compute-task-marker-name-v2-submittable
              template: compute-task-marker-name
            arguments:
              parameters:
                - name: task-type
                  value: "tr-alignment"
              artifacts:
                - name: task-payload
                  from: "{{inputs.artifacts.run-payload}}"
          - name: check-if-task-marker-exists
            depends: compute-run-alignment-task-marker-name
            templateRef:
              name: check-s3-object-exists-v1-submittable
              template: check-s3-object-exists
            arguments:
              parameters:
                - name: s3-key
                  value: "{{tasks.compute-run-alignment-task-marker-name.outputs.result}}"

          - name: check-if-run-alignment-already-in-s3-bucket
            templateRef:
              name: check-s3-object-exists-v1-submittable
              template: check-s3-object-exists
            arguments:
              parameters:
                - name: s3-key
                  value: "{{inputs.parameters.output_prefix}}{{inputs.parameters.output_filename}}"

          - name: check-work-avoidance-consistency
            depends: "check-if-task-marker-exists && check-if-run-alignment-already-in-s3-bucket"
            templateRef:
              name: resolve-work-avoidance-v1-submittable
              template: resolve-work-avoidance
            arguments:
              parameters:
                - name: marker-exists
                  value: "{{tasks.check-if-task-marker-exists.outputs.parameters.s3-object-exists}}"
                - name: output-artifact-exists
                  value: "{{tasks.check-if-run-alignment-already-in-s3-bucket.outputs.parameters.s3-object-exists}}"
                - name: overwrite-results
                  value: "{{inputs.parameters.overwrite-results}}"

          - name: get-run-alignment-pvc-size
            depends: check-work-avoidance-consistency.Succeeded
            when: "{{tasks.check-work-avoidance-consistency.outputs.parameters.avoid-work}} == false"
            templateRef:
              name: compute-pvc-size-v1-submittable
              template: compute-pvc-size
            arguments:
              parameters:
                - name: associated_files_size
                  value: "{{inputs.parameters.total_read_files_size}}"
                - name: size_factor
                  value: "20"

          - name: create-run-alignment-pvc
            depends: "get-run-alignment-pvc-size.Succeeded"
            templateRef:
              name: create-pvc-kubectl-v1-submittable
              template: create-pvc-kubectl
            arguments:
              parameters:
                - name: pvc-size
                  value: "{{tasks.get-run-alignment-pvc-size.outputs.parameters.pvc-size-formatted}}"
                - name: kubeconfig-path
                  value: "{{inputs.parameters.kubeconfig-path}}"

          - name: load-read-file-to-pvc
            depends: create-run-alignment-pvc
            template: ftp-read-file-to-pvc
            arguments:
              parameters:
                - name: pvc-name
                  value: "{{tasks.create-run-alignment-pvc.outputs.parameters.pvc-name}}"
                # Input file
                - name: first_read_file_key
                  value: "{{inputs.parameters.first_read_file_key}}"
                - name: first_read_file_name
                  value: "{{inputs.parameters.first_read_file_name}}"

          - name: execute-fastqc-cmd-for-original-read-file
            depends: load-read-file-to-pvc
            templateRef:
              name: fastqc-se-cmd-pvc-callablev1-submittable
              template: fastqc-cmd-pvc-callable
            arguments:
              parameters:
                - name: pvc-name
                  value: "{{tasks.create-run-alignment-pvc.outputs.parameters.pvc-name}}"
                # Input file
                - name: first_read_file_name
                  value: "{{inputs.parameters.first_read_file_name}}"
                # Output files
                - name: outdir
                  value: "{{inputs.parameters.fastqc_outdir}}"
                - name: outdir_s3_prefix
                  value: "{{inputs.parameters.fastqc_output_prefix}}"

          - name: execute-fastp-cmd
            depends: execute-fastqc-cmd-for-original-read-file
            templateRef:
              name: fastp-se-cmd-pvc-callable-v1-submittable
              template: fastp-cmd-pvc-callable
            arguments:
              parameters:
                - name: pvc-name
                  value: "{{tasks.create-run-alignment-pvc.outputs.parameters.pvc-name}}"
                # Input file
                - name: first_read_file_name
                  value: "{{inputs.parameters.first_read_file_name}}"
                # Output files
                - name: out_prefix
                  value: "{{inputs.parameters.read_files_output_prefix}}"

          - name: clean-up-original-rf-from-pvc
            depends: execute-fastp-cmd
            template: remove-rf-from-pvc
            arguments:
              parameters:
                - name: pvc-name
                  value: "{{tasks.create-run-alignment-pvc.outputs.parameters.pvc-name}}"
                - name: first_read_file_name
                  value: "{{inputs.parameters.first_read_file_name}}"

          - name: execute-fastqc-cmd-for-noAdapt-read-files
            depends: clean-up-original-rf-from-pvc
            templateRef:
              name: fastqc-se-cmd-pvc-callablev1-submittable
              template: fastqc-cmd-pvc-callable
            arguments:
              parameters:
                - name: pvc-name
                  value: "{{tasks.create-run-alignment-pvc.outputs.parameters.pvc-name}}"
                # Input file
                - name: first_read_file_name
                  value: "{{inputs.parameters.read_files_output_prefix}}.fastq.gz"
                # Output files
                - name: outdir
                  value: "{{inputs.parameters.fastqc_outdir}}"
                - name: outdir_s3_prefix
                  value: "{{inputs.parameters.fastqc_output_prefix}}"

          - name: execute-bowtie2-cmd
            depends: execute-fastqc-cmd-for-noAdapt-read-files
            templateRef:
              name: bowtie2-se-cmd-pvc-callable-v1-submittable
              template: dag-bowtie2-cmd-pvc-callable
            arguments:
              parameters:
                - name: pvc-name
                  value: "{{tasks.create-run-alignment-pvc.outputs.parameters.pvc-name}}"
                # Input file
                - name: first_read_file_name
                  value: "{{inputs.parameters.read_files_output_prefix}}.fastq.gz"
                - name: bowtie2_index_key
                  value: "{{inputs.parameters.bowtie2_index_key}}"
                - name: bowtie2_index_basename
                  value: "{{inputs.parameters.bowtie2_index_basename}}"
                # Output prefix
                - name: output_prefix
                  value: "{{inputs.parameters.output_prefix}}"
                - name: output_filename
                  value: "{{inputs.parameters.output_filename}}"

          - name: update-run-alignment-task-marker
            depends: "execute-bowtie2-cmd || check-work-avoidance-consistency.Failed"
            when: "{{tasks.execute-bowtie2-cmd.status}} == Succeeded"
            templateRef:
              name: update-task-marker-v2-submittable
              template: update-task-marker
            arguments:
              parameters:
                - name: task-marker-s3-key
                  value: "{{tasks.compute-run-alignment-task-marker-name.outputs.result}}"
              artifacts:
                - name: task-payload
                  from: "{{inputs.artifacts.run-payload}}"

          - name: delete-run-alignment-pvc
            depends: execute-bowtie2-cmd
            templateRef:
              name: delete-patch-pvc-kubectl-v1-submittable
              template: delete-patch-pvc-kubectl
            arguments:
              parameters:
                - name: pvc-name
                  value: "{{tasks.create-run-alignment-pvc.outputs.parameters.pvc-name}}"
                - name: kubeconfig-path
                  value: "{{inputs.parameters.kubeconfig-path}}"

          - name: print-output-info
            depends: (delete-run-alignment-pvc.Succeeded || get-run-alignment-pvc-size.Skipped)
            template: output-info
            arguments:
              parameters:
                - name: alignment-name
                  value: "{{inputs.parameters.output_prefix}}{{inputs.parameters.output_filename}}"


    - name: output-info
      retryStrategy:
        limit: "5"
        backoff:
          duration: "10s"
          factor: "2"
          maxDuration: "24h"
        retryPolicy: "OnError"
      inputs:
        parameters:
          - name: alignment-name
      container:
        image: ghcr.io/daugo/ensembl-reg-bash:latest
        command: [ bash, -c, -uef, -o, xtrace ]
        args: [ "echo \
                'Alignment file: {{inputs.parameters.alignment-name}} archived and available for downstream analysis'" ]


    - name: ftp-read-file-to-pvc
      retryStrategy:
        limit: "12"
        backoff:
          duration: "10s"
          factor: "2"
          maxDuration: "24h"
        retryPolicy: "Always"
      inputs:
        parameters:
          - name: pvc-name
          # Input file
          - name: first_read_file_key
          - name: first_read_file_name
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: '{{inputs.parameters.pvc-name}}'
      container:
        image: ghcr.io/daugo/ensembl-reg-bash:latest
        command: [ bash, -c, -uef, -o, xtrace ]
        args: [ "echo \
                Loading {{inputs.parameters.first_read_file_name}} to \
                {{inputs.parameters.pvc-name}} \
                && wget -q -O /mnt/vol/{{inputs.parameters.first_read_file_name}} {{inputs.parameters.first_read_file_key}} \
                && ls -altrh /mnt/vol/" ]
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol

    - name: read-file-to-pvc
      podSpecPatch: '{ "initContainers": [ { "name": "init", "resources": { "limits": { "cpu": "10000m", "memory": "60Gi" } } } ] }'
      retryStrategy:
        limit: "12"
        backoff:
          duration: "10s"
          factor: "2"
          maxDuration: "24h"
        retryPolicy: "Always"
      inputs:
        parameters:
          - name: pvc-name
          # Input file
          - name: first_read_file_key
          - name: first_read_file_name
        artifacts:
          - name: first_read_file
            path: "/mnt/vol/{{inputs.parameters.first_read_file_name}}"
            http:
              url: "{{inputs.parameters.first_read_file_key}}"
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: '{{inputs.parameters.pvc-name}}'
      container:
        image: ghcr.io/daugo/ensembl-reg-bash:latest
        command: [ bash, -c, -uef, -o, xtrace ]
        args: [ "echo \
                Loading {{inputs.parameters.first_read_file_name}} to \
                {{inputs.parameters.pvc-name}} \
                && ls -altrh /mnt/vol/" ]
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol

    - name: remove-rf-from-pvc
      retryStrategy:
        limit: "5"
        backoff:
          duration: "10s"
          factor: "2"
          maxDuration: "6h"
        retryPolicy: "OnError"
      inputs:
        parameters:
          - name: pvc-name
          # Read files to delete
          - name: first_read_file_name
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: '{{inputs.parameters.pvc-name}}'
      container:
        workingDir: /mnt/vol
        image: ghcr.io/daugo/ensembl-reg-bash:latest
        command: [ bash, -c, -uef, -o, xtrace ]
        args: [ "ls -altrh \
                && rm \
                -f -- \
                {{inputs.parameters.first_read_file_name}} \
                && ls -altrh" ]
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol