apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: s3-object-to-pvc-v1-submittable
spec:
  entrypoint: s3-object-to-pvc
  imagePullSecrets:
    - name: ghcr-pull-token

  templates:
    - name: s3-object-to-pvc
      inputs:
        parameters:
          - name: s3-key
          - name: filename
          - name: pvc-name
          - name: pvc-dir
            value: "/results/"
      dag:
        tasks:
          - name: s3-object-to-pvc
            template: copy-s3-object-to-pvc
            arguments:
              parameters:
                - name: s3-key
                  value: "{{inputs.parameters.s3-key}}"
                - name: filename
                  value: "{{inputs.parameters.filename}}"
                - name: pvc-name
                  value: "{{inputs.parameters.pvc-name}}"
                - name: pvc-dir
                  value: "{{inputs.parameters.pvc-dir}}"

    - name: copy-s3-object-to-pvc
      retryStrategy:
        limit: "5"
        backoff:
          duration: "10s"
          factor: "2"
        retryPolicy: "OnError"
      inputs:
        parameters:
          # S3 object location (Source)
          - name: s3-key
          # Destination
          - name: pvc-name
          - name: pvc-dir
          - name: filename
        artifacts:
          - name: run-alignments
            path: "/mnt/vol/{{inputs.parameters.filename}}"
            s3:
              key: "{{inputs.parameters.s3-key}}"
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: '{{inputs.parameters.pvc-name}}'
      container:
        workingDir: /mnt/vol/
        imagePullPolicy: Always
        image: ghcr.io/daugo/ensembl-reg-bash:latest
        command: [ bash, -c, -ue, -o, xtrace ]
        args: [ "ls -altrh" ]
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol
