apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: get-request-from-reg-pipelines-api-v-0.1.1
spec:
  entrypoint: get-request-from-reg-pipelines-api

  templates:
    - name: get-request-from-reg-pipelines-api
      retryStrategy:
        limit: "5"
        backoff:
          duration: "10s"
          factor: "2"
          maxDuration: "24h"
        retryPolicy: "OnError"
      inputs:
        parameters:
          - name: url
      script:
        image: dockerhub.ebi.ac.uk/ensreg/workflows/container-images/python-wf-helper:3.11.7_0.1.0
        command: [ python ]
        source: |
          import sys
          import json
          from urllib.request import urlopen
          
          def main() -> int:
          
            with urlopen("{{inputs.parameters.url}}") as response:
              payload = json.load(response)
          
            print(json.dumps(payload, indent=2))
        
            return 0
          
          if __name__ == '__main__':
            sys.exit(main())

