apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: handle-reg-pipeline-api-payload-response-v1-submittable
spec:
  entrypoint: handle-reg-pipeline-api-payload-response

  templates:
    - name: handle-reg-pipeline-api-payload-response
      inputs:
        parameters:
          - name: payload-response
          - name: count
      container:
        imagePullPolicy: Always
        image: ghcr.io/daugo/ensembl-reg-bash:latest
        command: [ bash, -c, -ue, -o, xtrace ]
        args: [
            "echo '{{inputs.parameters.payload-response}}' > /tmp/items \
             && echo '{{inputs.parameters.count}}' > /tmp/count"
          ]
      outputs:
        artifacts:
          - name: items
            path: /tmp/items
        parameters:
          - name: count
            valueFrom:
              path: /tmp/count
