apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: delete-file-from-pvc-v-0.1.0
spec:
  entrypoint: delete-file-from-pvc

  templates:
    - name: delete-file-from-pvc
      retryStrategy:
        limit: "5"
        backoff:
          duration: "10s"
          factor: "2"
        retryPolicy: "OnError"
      inputs:
        parameters:
          - name: pvc-name
          - name: file-path
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: '{{inputs.parameters.pvc-name}}'
      container:
        image: dockerhub.ebi.ac.uk/ensreg/workflows/container-images/bash:5.2.21
        workingDir: /mnt/vol
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
        command: [ bash, -c, -ue, -o, xtrace ]
        args: [ "ls -altrh \
                && rm -f {{inputs.parameters.file-path}} \
                && ls -altrh" ]
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol