# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: update-task-marker-v-0.1.0
spec:
  entrypoint: update-task-marker

  templates:
    - name: update-task-marker
      retryStrategy:
        limit: "5"
        backoff:
          duration: "10s"
          factor: "2"
        retryPolicy: "OnError"
      inputs:
        parameters:
          - name: task-marker-s3-key
          - name: task-payload

      script:
        image: dockerhub.ebi.ac.uk/ensreg/workflows/container-images/python-wf-helper:3.11.7_0.1.0
        workingDir: /mnt/vol
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
        command: [ python ]
        source: |
          from pathlib import Path
          import json
          import sys

          def main() -> int:

            task_payload = """{{inputs.parameters.task-payload}}"""
            task_data = json.loads(task_payload)
          
            # task_marker_s3_key = Path("{{inputs.parameters.task-marker-s3-key}}")

            with open("task_marker.json", mode="w") as f:
              json.dump(task_data, f, indent=2, sort_keys=True)

            return 0

          if __name__ == '__main__':
              sys.exit(main())
      outputs:
        artifacts:
          - name: task-marker
            path: /mnt/vol/task_marker.json
            archive:
              none: { }
            s3:
              key: "{{inputs.parameters.task-marker-s3-key}}"