apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Versioned workflow templates

  ## Tool Modules
  - fastp/fastp-se-cmd-pvc-callable-v-0.1.yaml
  - fastqc/fastqc-pe-cmd-pvc-callable-v-0.1.yaml
  - fastqc/fastqc-se-cmd-pvc-callable-v-0.1.yaml
  - ngmerge/ngmerge-cmd-pvc-callable-v-0.1.yaml
  - bowtie2/build/build-index-v-0.1.yaml
  - bowtie2/bowtie2-pe-cmd-pvc-callable-v-0.1.yaml
  - bowtie2/bowtie2-se-cmd-pvc-callable-v-0.1.yaml
  - samtools/samtools-sort-pvc-callable-v-0.1.yaml
  - samtools/samtools-sort-pvc-callable-v-0.2.yaml
  - export-peak/bed-to-bigbed-v-0.1.yaml

  ## Helper Modules
  - helpers/create-pvc-v-0.2.yaml
  - helpers/delete-pvc-v-0.1.yaml
  - helpers/compute-pvc-size-v-0.1.yaml
  - helpers/check-s3-object-exists-v-0.1.yaml
  - helpers/check-if-s3-objects-exist-v-0.1.yaml
  - helpers/copy-s3-object-to-pvc-v-0.1.yaml
  - helpers/copy-s3-prefix-objects-to-pvc-v-0.1.yaml
  - helpers/copy-from-pvc-to-s3-object-v-0.1.yaml
  - helpers/cp-s3-object-to-s3-v-0.1.yaml
  - helpers/compute-task-marker-name-v-0.1.yaml
  - helpers/compute-task-marker-name-v-0.2.yaml
  - helpers/resolve-work-avoidance-v-0.1.yaml
  - helpers/update-task-marker-v-0.1.yaml
  - helpers/update-task-marker-v-0.2.yaml
  - helpers/validate-expected-number-of-files-in-dir-v-0.1.yaml
  - helpers/get-wf-task-payload-by-index-v-0.1.yaml
  - helpers/get-request-from-reg-pipelines-api-v-0.1.yaml
  - helpers/get-request-from-reg-pipelines-api-v-0.2.yaml
  - helpers/expose-payload-fields-as-params-v-0.1.yaml
  - helpers/compute-file-metadata-pvc-callable-v-0.1.yaml
  - helpers/analysis-file-post-request-payload-v-0.1.yaml
  - helpers/compress-tgz-pvc-callable-v-0.1.yaml
  - helpers/decompress-tgz-pvc-callable-v-0.1.yaml
  - helpers/decompress-tgz-pvc-callable-v-0.2.yaml
  - helpers/copy-pvc-to-pvc-v-0.1.yaml
  - helpers/check-if-field-present-and-not-empty-v-0.1.yaml
  - helpers/compute-file-metadata-v-0.1.yaml

  - alignment/compute-get-rfs-alignment-tasks-url-v-0.1.yaml

  ## Sub-workflows
  - alignment/alignment-tasks.yaml
  - alignment/rfs-alignment.yaml
  - alignment/run-alignment-pe.yaml
  - alignment/run-alignment-se.yaml

  - peak-calling/genrich-tasks.yaml
  - peak-calling/genrich-values-v-0.2.yaml
  - peak-calling/genrich-values-v-0.1.yaml
  - peak-calling/genrich-values-cmd.yaml
  - peak-calling/open-chromatin-genrich-values-cmd.yaml
  - peak-calling/chip-seq-genrich-values-cmd.yaml

  - peak-calling/peak-calling-tasks.yaml
  - peak-calling/chip-seq-peaks-v-0.2.yaml
  - peak-calling/open-chromatin-peaks-v-0.2.yaml

  - peak-calling/controls/get-control-peak-calling-tasks.yaml
  - peak-calling/controls/control-peak-calling-for-mask-file.yaml

  - signal/signal-tasks.yaml
  - signal/genrich-pq-values-to-bigwig-pvc-callable-v-0.1.yaml

  - motif-mapping/get-motif-mapping-tasks.yaml

  - masked-regions/masked-regions-identification-v-0.1.yaml

  - export-peak/get-export-peak-task.yaml


  # Experimental Workflow Templates
  - alignment/.experimental/rfs-alignment-v3.yaml
  - helpers/.experimental/create-nfs-pvc-kubectl.yaml
  - helpers/.experimental/delete-s3-object.yaml
  - helpers/.experimental/delete-request-from-reg-pipelines-api.yaml
  - helpers/.experimental/s3-objects-to-pvc.yaml
  - helpers/.experimental/delete-task-marker.yaml
  - helpers/.experimental/list-objects-under-s3-prefix.yaml
  - helpers/.experimental/post-results-to-reg-pipelines-api.yaml