# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: compute-pvc-size-v1-submittable
spec:
  entrypoint: compute-pvc-size
  imagePullSecrets:
    - name: ghcr-pull-token
  podGC:
    strategy: OnPodSuccess

  templates:
    - name: compute-pvc-size
      retryStrategy:
        limit: "5"
        backoff:
          duration: "10s"
          factor: "2"
        retryPolicy: "OnError"
      inputs:
        parameters:
          - name: associated_files_size
          - name: size_factor
      script:
        workingDir: /mnt/vol
        image: ghcr.io/daugo/ensembl-reg-python:latest
        command: [ python ]
        source: |
          import sys
          
          def sizeof_fmt(num, suffix="B"):
            for unit in ["", "Ki", "Mi", "Gi", "Ti", "Pi", "Ei", "Zi"]:
                if abs(num) < 1024.0:
                    return f"{num:3.1f}{unit}{suffix}"
                num /= 1024.0
            return f"{num:.1f}Yi{suffix}"
          
          def main() -> int:
          
            plain_file_size = float("{{inputs.parameters.associated_files_size}}")
            size_factor = float("{{inputs.parameters.size_factor}}")
          
            plain_pvc_size = plain_file_size * size_factor
          
            pvc_size_formatted = sizeof_fmt(plain_pvc_size, suffix="")
          
            with open('pvc_size_formatted.txt', 'w') as f:
              f.write(pvc_size_formatted)
          
            return 0

          if __name__ == '__main__':
              sys.exit(main())
      outputs:
        parameters:
          - name: pvc-size-formatted
            valueFrom:
              path: pvc_size_formatted.txt