# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: get-task-payload-by-index-v1-submittable
spec:
  entrypoint: get-task-payload-by-index

  templates:
    - name: get-task-payload-by-index
      retryStrategy:
        limit: "5"
        backoff:
          duration: "10s"
          factor: "2"
          maxDuration: "24h"
        retryPolicy: "OnError"
      inputs:
        parameters:
          - name: index
        artifacts:
          - name: items
            path: /home/ensreg/workdir/items.json
      script:
        securityContext:
          runAsNonRoot: true
          runAsUser: 8737
          runAsGroup: 8737
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        image: dockerhub.ebi.ac.uk/ensreg/workflows/container-images/regulation-wf-python:3.11.7
        command: [ python ]
        source: |
          import sys
          import json
          import os
          
          def main() -> int:
          
          
            os.system('ls -altrh')
            os.system('pwd')
            os.system('whoami')
          
            with open('{{inputs.artifacts.items.path}}') as f:
              payload = json.load(f)
          
            with open('{{outputs.artifacts.task-payload.path}}', 'w') as f:
              f.write(json.dumps(payload[{{inputs.parameters.index}}], indent=2))
          
            return 0
          
          if __name__ == '__main__':
            sys.exit(main())
      outputs:
        parameters:
          - name: task-payload
            valueFrom:
              path: task-payload.json
          - name: task-payload-artifact-ref
            value: "tests/task-payload/{{workflow.name}}/{{pod.name}}/rfs-alg-task-payload.json"
        artifacts:
          - name: task-payload
            path: task-payload.json
            s3:
              key: "tests/task-payload/{{workflow.name}}/{{pod.name}}/rfs-alg-task-payload.json"
            archive:
              none: { }

